name: ikkimi
description: "Ứng dụng đọc truyện với khả năng scraping nội dung từ các website truyện"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # UI Components
  getwidget: ^7.0.0
  cached_network_image: ^3.4.1
  flutter_html: ^3.0.0-beta.2
  google_nav_bar: ^5.0.6

  # Icons
  flutter_svg: ^2.0.16
  iconsax: ^0.0.8

  # State Management & Navigation
  get: ^4.6.6

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0

  # UI Enhancements
  shimmer: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  smooth_page_indicator: ^2.0.1
  auto_size_text: ^3.0.0

  # Responsive & Layout
  flutter_screenutil: ^5.9.3
  responsive_builder: ^0.7.1
  flutter_layout_grid: ^2.0.8

  # Utilities
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.1

  # Web Scraping
  dio: ^5.7.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
